CREATE DATABASE ODB;
USE ODB;

CREATE TABLE Product (pid INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, pname VARCHAR(24) NOT NULL, pcost INT(6) NOT NULL, pmanufacturer VARCHAR(24) NOT NULL, category VARCHAR(24) NOT NULL);
CREATE TABLE Store (sid INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, sname VARCHAR(24) NOT NULL, scity VARCHAR(10) NOT NULL, sstate VARCHAR(2) NOT NULL, scountry VARCHAR(24) NOT NULL);
CREATE TABLE Customer (cid INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, cname VARCHAR(24) NOT NULL, caddress VARCHAR(30) NOT NULL);
CREATE TABLE Transaction (tid INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, pid INT(6) NOT NULL FOREIGN KEY, cid INT(6) NOT NULL FOREIGN KEY, amount INT(6) NOT NULL, totalcost INT(50) NOT NULL, day INT(2) NOT NULL, month INT(2) NOT NULL, year INT(4) NOT NULL, sid INT(6) NOT NULL FOREIGN KEY);

CREATE DATABASE ADB;
USE ADB;


CREATE TABLE fact(pid INT(6) NOT NULL, lid INT(6) NOT NULL, day INT(2) NOT NULL, month INT(2) NOT NULL, year INT(4) NOT NULL, sale INT(50) NOT NULL);
CREATE TABLE productdim(pid INT(6) NOT NULL PRIMARY KEY, pname VARCHAR(24) NOT NULL, pcategory VARCHAR(24) NOT NULL);
CREATE TABLE locationdim(lid INT(6) NOT NULL PRIMARY KEY, city VARCHAR(24) NOT NULL, state VARCHAR(24) NOT NULL, country VARCHAR(24) NOT NULL);
CREATE TABLE timedim(day INT(2) NOT NULL, month INT(2) NOT NULL, year INT(4) NOT NULL);

ALTER TABLE fact ADD PRIMARY KEY(pid, lid , day, month, year);
ALTER TABLE timedim ADD PRIMARY KEY(day,month,year);
